version: '1.0'
name: release
displayName: 构建燕几图数据库
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ''
  pr:
    branches:
      prefix:
        - ''
stages:
  - name: build-stage
    displayName: 构建燕几图数据库
    strategy: naturally
    trigger: auto
    steps:
      - step: execute@docker
        name: build
        displayName: 打包
        certificate: bd032500-8921-013c-01b0-261cd6c176b8
        image: swr.cn-north-4.myhuaweicloud.com/rustica/neon-comppute-hce-pg16:latest
        command:
          - VERSION=${GITEE_COMMIT} bash .workflow/build.sh
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - .output/neon-rusticadb-${GITEE_COMMIT}.zip
        strategy: {}
      - step: execute@docker
        name: upload
        displayName: 上传
        certificate: bd032500-8921-013c-01b0-261cd6c176b8
        image: swr.cn-north-4.myhuaweicloud.com/rustica/obsutil:latest
        command:
          - mkdir .output
          - curl -o artifact_BUILD_ARTIFACT.tar.gz ${BUILD_ARTIFACT}
          - tar -zxvf artifact_BUILD_ARTIFACT.tar.gz -C .output/
          - VERSION=${GITEE_COMMIT} bash .workflow/upload.sh
        strategy: {}
        dependsOn: build
strategy:
  blocking: true
  stepTimeout: 10
